import type { Profile, Gig, Review, Booking, Order, Conversation, Message } from '../types';

export const MOCK_PROVIDERS: Profile[] = [
  {
    id: 'provider-1',
    email: 'mike.johnson@email.com',
    full_name: 'Mike Johnson',
    avatar_url: null,
    role: 'provider',
    phone: '+1 (555) 123-4567',
    bio: 'Licensed master plumber with 15+ years of experience. Specializing in emergency repairs, pipe installations, and bathroom renovations. Available 24/7 for urgent calls.',
    location: 'new_york',
    is_verified: true,
    created_at: '2023-03-15T00:00:00Z',
    rating_avg: 4.9,
    review_count: 127,
    completion_rate: 98,
    response_time: 'within 1 hour',
    total_earnings: 85000,
    balance: 12500,
    pending_earnings: 3200,
  },
  {
    id: 'provider-2',
    email: 'sarah.williams@email.com',
    full_name: 'Sarah Williams',
    avatar_url: null,
    role: 'provider',
    phone: '+1 (555) 234-5678',
    bio: 'Professional electrician and certified electrical contractor. Residential and commercial wiring, panel upgrades, and smart home installations.',
    location: 'los_angeles',
    is_verified: true,
    created_at: '2023-06-20T00:00:00Z',
    rating_avg: 4.8,
    review_count: 89,
    completion_rate: 97,
    response_time: 'within 2 hours',
    total_earnings: 62000,
    balance: 8900,
    pending_earnings: 1500,
  },
  {
    id: 'provider-3',
    email: 'carlos.garcia@email.com',
    full_name: 'Carlos Garcia',
    avatar_url: null,
    role: 'provider',
    phone: '+1 (555) 345-6789',
    bio: 'Expert landscaper and garden designer. Transform your outdoor spaces with sustainable, beautiful gardens. Specializing in native plants and water-efficient designs.',
    location: 'austin',
    is_verified: true,
    created_at: '2023-01-10T00:00:00Z',
    rating_avg: 5.0,
    review_count: 203,
    completion_rate: 99,
    response_time: 'within 30 mins',
    total_earnings: 95000,
    balance: 15600,
    pending_earnings: 4200,
  },
  {
    id: 'provider-4',
    email: 'lisa.chen@email.com',
    full_name: 'Lisa Chen',
    avatar_url: null,
    role: 'provider',
    phone: '+1 (555) 456-7890',
    bio: 'Master tailor with fashion design background. Custom suits, wedding dresses, alterations, and repairs. Using only premium fabrics and traditional techniques.',
    location: 'chicago',
    is_verified: false,
    created_at: '2024-01-05T00:00:00Z',
    rating_avg: 4.7,
    review_count: 45,
    completion_rate: 95,
    response_time: 'within 3 hours',
    total_earnings: 28000,
    balance: 4200,
    pending_earnings: 800,
  },
  {
    id: 'provider-5',
    email: 'james.brown@email.com',
    full_name: 'James Brown',
    avatar_url: null,
    role: 'provider',
    phone: '+1 (555) 567-8901',
    bio: 'Professional painter with an eye for detail. Interior and exterior painting, wallpaper installation, and decorative finishes. Eco-friendly paints available.',
    location: 'seattle',
    is_verified: true,
    created_at: '2023-09-01T00:00:00Z',
    rating_avg: 4.6,
    review_count: 67,
    completion_rate: 96,
    response_time: 'within 1 hour',
    total_earnings: 45000,
    balance: 6700,
    pending_earnings: 2100,
  },
  {
    id: 'provider-6',
    email: 'maria.rodriguez@email.com',
    full_name: 'Maria Rodriguez',
    avatar_url: null,
    role: 'provider',
    phone: '+1 (555) 678-9012',
    bio: 'Experienced house cleaner and organizing specialist. Deep cleaning, move-in/move-out cleaning, and regular maintenance. Green cleaning products used.',
    location: 'miami',
    is_verified: true,
    created_at: '2023-04-15T00:00:00Z',
    rating_avg: 4.9,
    review_count: 156,
    completion_rate: 99,
    response_time: 'within 1 hour',
    total_earnings: 72000,
    balance: 9800,
    pending_earnings: 2800,
  },
  {
    id: 'provider-7',
    email: 'david.kim@email.com',
    full_name: 'David Kim',
    avatar_url: null,
    role: 'provider',
    phone: '+1 (555) 789-0123',
    bio: 'Auto mechanic with 20+ years of experience. Full diagnostics, engine repair, brake service, and oil changes. Honest pricing and quality work guaranteed.',
    location: 'houston',
    is_verified: true,
    created_at: '2022-11-20T00:00:00Z',
    rating_avg: 4.8,
    review_count: 178,
    completion_rate: 97,
    response_time: 'within 2 hours',
    total_earnings: 110000,
    balance: 18500,
    pending_earnings: 5600,
  },
  {
    id: 'provider-8',
    email: 'tom.wilson@email.com',
    full_name: 'Tom Wilson',
    avatar_url: null,
    role: 'provider',
    phone: '+1 (555) 890-1234',
    bio: 'Skilled carpenter specializing in custom furniture, cabinetry, and home renovations. Precision craftsmanship with sustainable hardwoods.',
    location: 'portland',
    is_verified: true,
    created_at: '2023-07-12T00:00:00Z',
    rating_avg: 4.9,
    review_count: 92,
    completion_rate: 98,
    response_time: 'within 2 hours',
    total_earnings: 78000,
    balance: 11200,
    pending_earnings: 3400,
  },
];

export const MOCK_CLIENTS: Profile[] = [
  {
    id: 'client-1',
    email: 'john.doe@email.com',
    full_name: 'John Doe',
    avatar_url: null,
    role: 'client',
    phone: '+1 (555) 111-2222',
    bio: null,
    location: 'new_york',
    is_verified: false,
    created_at: '2024-01-01T00:00:00Z',
    rating_avg: 0,
    review_count: 0,
    completion_rate: 0,
    response_time: null,
    total_earnings: 0,
    balance: 0,
    pending_earnings: 0,
  },
  {
    id: 'client-2',
    email: 'jane.smith@email.com',
    full_name: 'Jane Smith',
    avatar_url: null,
    role: 'client',
    phone: '+1 (555) 333-4444',
    bio: null,
    location: 'los_angeles',
    is_verified: false,
    created_at: '2024-02-15T00:00:00Z',
    rating_avg: 0,
    review_count: 0,
    completion_rate: 0,
    response_time: null,
    total_earnings: 0,
    balance: 0,
    pending_earnings: 0,
  },
];

export const MOCK_GIGS: Gig[] = [
  {
    id: 'gig-1',
    provider_id: 'provider-1',
    title: 'Professional Plumbing Repair & Installation',
    description: 'I provide expert plumbing services including emergency leak repairs, pipe installation, drain cleaning, toilet and faucet repairs, water heater installation, and bathroom remodeling. All work comes with a satisfaction guarantee and I always clean up after the job is done. Available for both residential and commercial properties.',
    category: 'plumbing',
    subcategory: null,
    location: 'new_york',
    pricing_tiers: [
      { name: 'Basic', price: 75, description: 'Simple repair (faucet, toilet, minor leak)', delivery_days: 1, features: ['Single fixture repair', 'Parts inspection', '30-day warranty'] },
      { name: 'Standard', price: 200, description: 'Medium repair or installation', delivery_days: 2, features: ['Up to 3 fixtures', 'Full diagnostic', 'Parts included', '90-day warranty'] },
      { name: 'Premium', price: 500, description: 'Major installation or renovation', delivery_days: 5, features: ['Full bathroom/kitchen plumbing', 'Premium materials', 'Code compliance check', '1-year warranty', 'Emergency support'] },
    ],
    photos: [],
    rating_avg: 4.9,
    review_count: 127,
    is_active: true,
    created_at: '2023-04-01T00:00:00Z',
    updated_at: '2024-10-15T00:00:00Z',
    provider: MOCK_PROVIDERS[0],
  },
  {
    id: 'gig-2',
    provider_id: 'provider-2',
    title: 'Residential & Commercial Electrical Services',
    description: 'Licensed electrician offering a full range of electrical services. From outlet installation to complete home rewiring, I handle it all safely and up to code. Smart home setup, EV charger installation, and energy-efficient lighting upgrades available.',
    category: 'electrical',
    subcategory: null,
    location: 'los_angeles',
    pricing_tiers: [
      { name: 'Basic', price: 85, description: 'Outlet/switch installation or repair', delivery_days: 1, features: ['Single outlet/switch', 'Safety inspection', '30-day warranty'] },
      { name: 'Standard', price: 300, description: 'Panel upgrade or circuit installation', delivery_days: 3, features: ['Up to 4 circuits', 'Load balancing', 'Code compliance', '90-day warranty'] },
      { name: 'Premium', price: 800, description: 'Complete home rewiring or smart home', delivery_days: 7, features: ['Whole-home service', 'Smart panel install', 'EV charger ready', '2-year warranty', 'Priority support'] },
    ],
    photos: [],
    rating_avg: 4.8,
    review_count: 89,
    is_active: true,
    created_at: '2023-07-15T00:00:00Z',
    updated_at: '2024-11-01T00:00:00Z',
    provider: MOCK_PROVIDERS[1],
  },
  {
    id: 'gig-3',
    provider_id: 'provider-3',
    title: 'Garden Design & Landscape Transformation',
    description: 'Transform your outdoor space into a beautiful, sustainable garden. I specialize in native plant landscaping, drought-resistant designs, vegetable gardens, and complete yard makeovers. Every project starts with a personalized consultation.',
    category: 'gardening',
    subcategory: null,
    location: 'austin',
    pricing_tiers: [
      { name: 'Basic', price: 100, description: 'Garden consultation & small planting', delivery_days: 1, features: ['1-hour consultation', 'Plant selection guide', 'Small bed planting'] },
      { name: 'Standard', price: 400, description: 'Medium garden design & installation', delivery_days: 4, features: ['Custom design plan', 'Up to 500 sq ft', 'Plants included', 'Irrigation setup'] },
      { name: 'Premium', price: 1200, description: 'Complete landscape transformation', delivery_days: 10, features: ['Full yard design', 'Hardscaping included', 'Irrigation system', 'Lighting', '6-month plant guarantee'] },
    ],
    photos: [],
    rating_avg: 5.0,
    review_count: 203,
    is_active: true,
    created_at: '2023-02-01T00:00:00Z',
    updated_at: '2024-09-20T00:00:00Z',
    provider: MOCK_PROVIDERS[2],
  },
  {
    id: 'gig-4',
    provider_id: 'provider-4',
    title: 'Custom Tailoring & Clothing Alterations',
    description: 'Expert tailoring services for all your clothing needs. Custom suits and dresses, wedding attire, professional alterations, and repairs. Using premium fabrics and traditional hand-sewing techniques for the perfect fit.',
    category: 'tailoring',
    subcategory: null,
    location: 'chicago',
    pricing_tiers: [
      { name: 'Basic', price: 35, description: 'Simple alterations (hem, buttons)', delivery_days: 2, features: ['Basic hemming', 'Button replacement', 'Minor repairs'] },
      { name: 'Standard', price: 150, description: 'Complex alterations or custom piece', delivery_days: 7, features: ['Full garment alteration', 'Custom fitting', 'Premium thread', 'One revision'] },
      { name: 'Premium', price: 500, description: 'Custom suit or dress from scratch', delivery_days: 21, features: ['Custom measurements', 'Fabric selection', 'Multiple fittings', 'Hand-finished details', 'Unlimited revisions'] },
    ],
    photos: [],
    rating_avg: 4.7,
    review_count: 45,
    is_active: true,
    created_at: '2024-02-01T00:00:00Z',
    updated_at: '2024-11-10T00:00:00Z',
    provider: MOCK_PROVIDERS[3],
  },
  {
    id: 'gig-5',
    provider_id: 'provider-5',
    title: 'Interior & Exterior House Painting',
    description: 'Professional painting services for homes and businesses. Expert color consultation, surface preparation, and flawless application. Using premium, eco-friendly paints that last for years. All furniture and floors protected during work.',
    category: 'painting',
    subcategory: null,
    location: 'seattle',
    pricing_tiers: [
      { name: 'Basic', price: 150, description: 'Single room painting', delivery_days: 1, features: ['1 room (up to 12x12)', 'Wall prep included', 'Two coats', 'Paint included'] },
      { name: 'Standard', price: 500, description: 'Multi-room or exterior accent', delivery_days: 3, features: ['Up to 3 rooms', 'Color consultation', 'Trim painting', 'Premium paint'] },
      { name: 'Premium', price: 2000, description: 'Whole house interior or exterior', delivery_days: 7, features: ['Whole house coverage', 'Surface repair', 'Premium/eco paint', 'Detailed trim work', '3-year warranty'] },
    ],
    photos: [],
    rating_avg: 4.6,
    review_count: 67,
    is_active: true,
    created_at: '2023-10-01T00:00:00Z',
    updated_at: '2024-08-05T00:00:00Z',
    provider: MOCK_PROVIDERS[4],
  },
  {
    id: 'gig-6',
    provider_id: 'provider-6',
    title: 'Deep Cleaning & Home Organization',
    description: 'Thorough cleaning and organization services for your home or office. Using eco-friendly products, I provide deep cleaning that reaches every corner. Move-in/move-out cleaning, regular maintenance, and complete home organization available.',
    category: 'cleaning',
    subcategory: null,
    location: 'miami',
    pricing_tiers: [
      { name: 'Basic', price: 80, description: 'Standard home cleaning', delivery_days: 1, features: ['Up to 2 bedrooms', 'Kitchen & bathroom', 'Vacuuming & mopping', 'Green products'] },
      { name: 'Standard', price: 200, description: 'Deep cleaning service', delivery_days: 1, features: ['Whole home deep clean', 'Appliance cleaning', 'Window interiors', 'Organization tips'] },
      { name: 'Premium', price: 450, description: 'Deep clean + full organization', delivery_days: 2, features: ['Complete deep clean', 'Closet organization', 'Pantry setup', 'Decluttering', 'Custom storage solutions'] },
    ],
    photos: [],
    rating_avg: 4.9,
    review_count: 156,
    is_active: true,
    created_at: '2023-05-15T00:00:00Z',
    updated_at: '2024-11-15T00:00:00Z',
    provider: MOCK_PROVIDERS[5],
  },
  {
    id: 'gig-7',
    provider_id: 'provider-7',
    title: 'Complete Auto Repair & Maintenance',
    description: 'Full-service auto repair with transparent pricing. Engine diagnostics, brake service, oil changes, tire rotation, AC repair, and more. Using OEM-quality parts with honest assessments - no unnecessary upsells.',
    category: 'auto_repair',
    subcategory: null,
    location: 'houston',
    pricing_tiers: [
      { name: 'Basic', price: 50, description: 'Oil change & basic inspection', delivery_days: 1, features: ['Oil & filter change', '23-point inspection', 'Fluid top-off', 'Tire pressure check'] },
      { name: 'Standard', price: 250, description: 'Brake service or tune-up', delivery_days: 2, features: ['Full brake service', 'Diagnostic scan', 'Parts included', '6-month warranty'] },
      { name: 'Premium', price: 800, description: 'Major repair or overhaul', delivery_days: 5, features: ['Engine/transmission work', 'OEM parts', 'Full diagnostic', 'Loaner car available', '1-year warranty'] },
    ],
    photos: [],
    rating_avg: 4.8,
    review_count: 178,
    is_active: true,
    created_at: '2022-12-01T00:00:00Z',
    updated_at: '2024-10-25T00:00:00Z',
    provider: MOCK_PROVIDERS[6],
  },
  {
    id: 'gig-8',
    provider_id: 'provider-8',
    title: 'Custom Carpentry & Furniture Building',
    description: 'Handcrafted woodworking for your home. Custom shelving, built-in cabinetry, furniture repair, deck building, and more. Every piece is made with care using sustainably sourced hardwoods.',
    category: 'carpentry',
    subcategory: null,
    location: 'portland',
    pricing_tiers: [
      { name: 'Basic', price: 100, description: 'Small repair or simple project', delivery_days: 2, features: ['Furniture repair', 'Shelf installation', 'Minor fixes', 'Wood stain match'] },
      { name: 'Standard', price: 500, description: 'Custom shelving or small furniture', delivery_days: 7, features: ['Custom design', 'Quality hardwood', 'Finishing included', 'Delivery & install'] },
      { name: 'Premium', price: 2000, description: 'Built-in cabinetry or deck', delivery_days: 14, features: ['Full custom build', 'Premium materials', '3D design preview', 'Installation', '5-year warranty'] },
    ],
    photos: [],
    rating_avg: 4.9,
    review_count: 92,
    is_active: true,
    created_at: '2023-08-01T00:00:00Z',
    updated_at: '2024-11-05T00:00:00Z',
    provider: MOCK_PROVIDERS[7],
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'review-1',
    gig_id: 'gig-1',
    order_id: 'order-1',
    client_id: 'client-1',
    provider_id: 'provider-1',
    rating: 5,
    comment: 'Mike was fantastic! Arrived on time, diagnosed the leak quickly, and had everything fixed within an hour. Very professional and clean. Highly recommend!',
    provider_response: 'Thank you, John! It was a pleasure working with you. Don\'t hesitate to reach out if you need anything else.',
    created_at: '2024-10-20T00:00:00Z',
    client: MOCK_CLIENTS[0],
  },
  {
    id: 'review-2',
    gig_id: 'gig-1',
    order_id: 'order-2',
    client_id: 'client-2',
    provider_id: 'provider-1',
    rating: 5,
    comment: 'Emergency call at 10pm and Mike was here within 30 minutes. Fixed a burst pipe and saved us from major water damage. Worth every penny!',
    provider_response: null,
    created_at: '2024-09-15T00:00:00Z',
    client: MOCK_CLIENTS[1],
  },
  {
    id: 'review-3',
    gig_id: 'gig-3',
    order_id: 'order-3',
    client_id: 'client-1',
    provider_id: 'provider-3',
    rating: 5,
    comment: 'Carlos completely transformed our backyard! The design was beautiful and he was very knowledgeable about which plants would thrive in our climate. The garden looks amazing.',
    provider_response: 'Thank you so much! Your yard had great potential and it was a joy to work with. Enjoy the garden!',
    created_at: '2024-11-01T00:00:00Z',
    client: MOCK_CLIENTS[0],
  },
  {
    id: 'review-4',
    gig_id: 'gig-6',
    order_id: 'order-4',
    client_id: 'client-2',
    provider_id: 'provider-6',
    rating: 5,
    comment: 'Maria did an incredible job deep cleaning our apartment before we moved out. Got our full deposit back! She even organized our closets in the new place. Truly exceptional service.',
    provider_response: null,
    created_at: '2024-10-05T00:00:00Z',
    client: MOCK_CLIENTS[1],
  },
  {
    id: 'review-5',
    gig_id: 'gig-2',
    order_id: 'order-5',
    client_id: 'client-1',
    provider_id: 'provider-2',
    rating: 4,
    comment: 'Great work on the electrical panel upgrade. Sarah was very thorough and explained everything clearly. Took a bit longer than expected but the quality was excellent.',
    provider_response: 'Thanks for your patience, John. Panel upgrades need to be done right - glad you\'re happy with the result!',
    created_at: '2024-08-20T00:00:00Z',
    client: MOCK_CLIENTS[0],
  },
  {
    id: 'review-6',
    gig_id: 'gig-7',
    order_id: 'order-6',
    client_id: 'client-2',
    provider_id: 'provider-7',
    rating: 5,
    comment: 'David is the most honest mechanic I\'ve ever worked with. He actually told me what I did NOT need, saving me hundreds. Engine runs like new after the tune-up.',
    provider_response: null,
    created_at: '2024-09-10T00:00:00Z',
    client: MOCK_CLIENTS[1],
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'booking-1',
    gig_id: 'gig-1',
    client_id: 'client-1',
    provider_id: 'provider-1',
    tier: 'Standard',
    price: 200,
    scheduled_date: '2024-12-15',
    scheduled_time: '10:00 AM',
    status: 'completed',
    notes: 'Kitchen faucet is leaking and bathroom drain is slow.',
    created_at: '2024-12-10T00:00:00Z',
    updated_at: '2024-12-15T16:00:00Z',
    gig: MOCK_GIGS[0],
  },
  {
    id: 'booking-2',
    gig_id: 'gig-3',
    client_id: 'client-1',
    provider_id: 'provider-3',
    tier: 'Premium',
    price: 1200,
    scheduled_date: '2025-01-20',
    scheduled_time: '09:00 AM',
    status: 'confirmed',
    notes: 'Complete backyard transformation. Want drought-resistant plants.',
    created_at: '2025-01-10T00:00:00Z',
    updated_at: '2025-01-12T00:00:00Z',
    gig: MOCK_GIGS[2],
  },
  {
    id: 'booking-3',
    gig_id: 'gig-6',
    client_id: 'client-2',
    provider_id: 'provider-6',
    tier: 'Standard',
    price: 200,
    scheduled_date: '2025-01-25',
    scheduled_time: '08:00 AM',
    status: 'in_progress',
    notes: 'Deep clean entire 3-bedroom apartment.',
    created_at: '2025-01-20T00:00:00Z',
    updated_at: '2025-01-25T08:00:00Z',
    gig: MOCK_GIGS[5],
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'order-1',
    booking_id: 'booking-1',
    client_id: 'client-1',
    provider_id: 'provider-1',
    amount: 200,
    platform_fee: 30,
    provider_earnings: 170,
    payment_intent_id: 'pi_mock_1',
    payment_status: 'released',
    status: 'completed',
    created_at: '2024-12-10T00:00:00Z',
    completed_at: '2024-12-15T16:00:00Z',
    booking: MOCK_BOOKINGS[0],
  },
  {
    id: 'order-2',
    booking_id: 'booking-2',
    client_id: 'client-1',
    provider_id: 'provider-3',
    amount: 1200,
    platform_fee: 180,
    provider_earnings: 1020,
    payment_intent_id: 'pi_mock_2',
    payment_status: 'held',
    status: 'in_progress',
    created_at: '2025-01-10T00:00:00Z',
    completed_at: null,
    booking: MOCK_BOOKINGS[1],
  },
  {
    id: 'order-3',
    booking_id: 'booking-3',
    client_id: 'client-2',
    provider_id: 'provider-6',
    amount: 200,
    platform_fee: 30,
    provider_earnings: 170,
    payment_intent_id: 'pi_mock_3',
    payment_status: 'held',
    status: 'in_progress',
    created_at: '2025-01-20T00:00:00Z',
    completed_at: null,
    booking: MOCK_BOOKINGS[2],
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-1',
    participant_1: 'client-1',
    participant_2: 'provider-1',
    gig_id: 'gig-1',
    last_message: 'Thanks Mike! See you Monday at 10am.',
    last_message_at: '2024-12-12T14:30:00Z',
    created_at: '2024-12-10T09:00:00Z',
    other_user: MOCK_PROVIDERS[0],
    gig: MOCK_GIGS[0],
    unread_count: 0,
  },
  {
    id: 'conv-2',
    participant_1: 'client-1',
    participant_2: 'provider-3',
    gig_id: 'gig-3',
    last_message: 'I\'ll send you the design mockup by tomorrow evening.',
    last_message_at: '2025-01-15T10:00:00Z',
    created_at: '2025-01-10T11:00:00Z',
    other_user: MOCK_PROVIDERS[2],
    gig: MOCK_GIGS[2],
    unread_count: 1,
  },
];

export const MOCK_MESSAGES: Record<string, Message[]> = {
  'conv-1': [
    { id: 'msg-1', conversation_id: 'conv-1', sender_id: 'client-1', content: 'Hi Mike, I have a leaking kitchen faucet and a slow bathroom drain. Are you available next week?', is_read: true, created_at: '2024-12-10T09:00:00Z' },
    { id: 'msg-2', conversation_id: 'conv-1', sender_id: 'provider-1', content: 'Hi John! Yes, I can come by Monday morning. A leaking faucet and slow drain would fall under my Standard package. I\'ll bring all the tools and parts needed.', is_read: true, created_at: '2024-12-10T09:15:00Z' },
    { id: 'msg-3', conversation_id: 'conv-1', sender_id: 'client-1', content: 'That sounds great. Monday at 10am works for me. What\'s included in the Standard package?', is_read: true, created_at: '2024-12-10T09:30:00Z' },
    { id: 'msg-4', conversation_id: 'conv-1', sender_id: 'provider-1', content: 'The Standard package covers up to 3 fixtures, includes a full diagnostic, parts, and comes with a 90-day warranty. It\'s $200 total.', is_read: true, created_at: '2024-12-10T09:45:00Z' },
    { id: 'msg-5', conversation_id: 'conv-1', sender_id: 'client-1', content: 'Perfect, let\'s go with that. I\'ll book it now.', is_read: true, created_at: '2024-12-10T10:00:00Z' },
    { id: 'msg-6', conversation_id: 'conv-1', sender_id: 'provider-1', content: 'Booking confirmed! I\'ll see you Monday at 10am. Make sure someone is home to let me in. 👍', is_read: true, created_at: '2024-12-10T10:05:00Z' },
    { id: 'msg-7', conversation_id: 'conv-1', sender_id: 'client-1', content: 'Thanks Mike! See you Monday at 10am.', is_read: true, created_at: '2024-12-12T14:30:00Z' },
  ],
  'conv-2': [
    { id: 'msg-8', conversation_id: 'conv-2', sender_id: 'client-1', content: 'Hi Carlos! I saw your amazing portfolio. We have a large backyard that needs a complete makeover. We want drought-resistant plants since we\'re in Austin.', is_read: true, created_at: '2025-01-10T11:00:00Z' },
    { id: 'msg-9', conversation_id: 'conv-2', sender_id: 'provider-3', content: 'Hello John! Thank you for reaching out. Drought-resistant gardens are my specialty here in Austin. Could you send me some photos of your current backyard and tell me the approximate size?', is_read: true, created_at: '2025-01-10T11:30:00Z' },
    { id: 'msg-10', conversation_id: 'conv-2', sender_id: 'client-1', content: 'It\'s about 1500 sq ft. We want a mix of native flowers, some raised beds for vegetables, and a small patio area.', is_read: true, created_at: '2025-01-10T12:00:00Z' },
    { id: 'msg-11', conversation_id: 'conv-2', sender_id: 'provider-3', content: 'That sounds like a wonderful project! I\'d recommend the Premium package for a space that size. It includes the full design, hardscaping for the patio, irrigation system, and a 6-month plant guarantee.', is_read: true, created_at: '2025-01-10T12:30:00Z' },
    { id: 'msg-12', conversation_id: 'conv-2', sender_id: 'client-1', content: 'Let\'s do it! When can you start?', is_read: true, created_at: '2025-01-10T13:00:00Z' },
    { id: 'msg-13', conversation_id: 'conv-2', sender_id: 'provider-3', content: 'I\'ll send you the design mockup by tomorrow evening.', is_read: false, created_at: '2025-01-15T10:00:00Z' },
  ],
};
