import type { Profile, Gig, Review, Booking, Order, Conversation, Message } from '../types';

export const MOCK_PROVIDERS: Profile[] = [
  {
    id: 'provider-1',
    email: 'jean.paul@email.com',
    full_name: 'Jean-Paul Mbarga',
    avatar_url: null,
    role: 'provider',
    phone: '+237 6 99 12 34 56',
    bio: 'Plombier professionnel avec 15 ans d\'expérience. Spécialisé dans les réparations d\'urgence, installations de tuyauterie et rénovation de salles de bain. Disponible 24h/24 pour les urgences.',
    location: 'douala',
    country: 'CM',
    is_verified: true,
    verifications: ['gov_id', 'phone', 'portfolio'],
    created_at: '2023-03-15T00:00:00Z',
    rating_avg: 4.9,
    review_count: 127,
    completion_rate: 98,
    response_time: 'within 1 hour',
    total_earnings: 4500000,
    balance: 850000,
    pending_earnings: 125000,
    is_available_now: true,
    offers_emergency: true,
    video_intro_url: null,
  },
  {
    id: 'provider-2',
    email: 'sarah.kouame@email.com',
    full_name: 'Sarah Kouamé',
    avatar_url: null,
    role: 'provider',
    phone: '+225 07 89 12 34',
    bio: 'Électricienne certifiée et entrepreneuse. Câblage résidentiel et commercial, mises à niveau de panneaux et installations de systèmes solaires.',
    location: 'abidjan',
    country: 'CI',
    is_verified: true,
    verifications: ['gov_id', 'phone'],
    created_at: '2023-06-20T00:00:00Z',
    rating_avg: 4.8,
    review_count: 89,
    completion_rate: 97,
    response_time: 'within 2 hours',
    total_earnings: 3200000,
    balance: 620000,
    pending_earnings: 95000,
    is_available_now: false,
    offers_emergency: true,
    video_intro_url: null,
  },
  {
    id: 'provider-3',
    email: 'amadou.diallo@email.com',
    full_name: 'Amadou Diallo',
    avatar_url: null,
    role: 'provider',
    phone: '+237 6 77 45 67 89',
    bio: 'Jardinier paysagiste expert. Transformez vos espaces extérieurs avec des jardins durables et magnifiques. Spécialisé en plantes tropicales et aménagements paysagers.',
    location: 'yaounde',
    country: 'CM',
    is_verified: true,
    verifications: ['gov_id', 'phone', 'portfolio'],
    created_at: '2023-01-10T00:00:00Z',
    rating_avg: 5.0,
    review_count: 203,
    completion_rate: 99,
    response_time: 'within 30 mins',
    total_earnings: 5800000,
    balance: 980000,
    pending_earnings: 250000,
    is_available_now: true,
    offers_emergency: false,
    video_intro_url: null,
  },
  {
    id: 'provider-4',
    email: 'fatou.traore@email.com',
    full_name: 'Fatou Traoré',
    avatar_url: null,
    role: 'provider',
    phone: '+225 05 67 89 01',
    bio: 'Couturière experte avec une formation en design de mode. Costumes sur mesure, robes de mariée, retouches et réparations. Utilisation de tissus africains premium et techniques traditionnelles.',
    location: 'bouake',
    country: 'CI',
    is_verified: false,
    verifications: ['phone'],
    created_at: '2024-01-05T00:00:00Z',
    rating_avg: 4.7,
    review_count: 45,
    completion_rate: 95,
    response_time: 'within 3 hours',
    total_earnings: 1800000,
    balance: 280000,
    pending_earnings: 55000,
    is_available_now: true,
    offers_emergency: false,
    video_intro_url: null,
  },
  {
    id: 'provider-5',
    email: 'paul.nganou@email.com',
    full_name: 'Paul Nganou',
    avatar_url: null,
    role: 'provider',
    phone: '+237 6 55 67 89 01',
    bio: 'Peintre professionnel avec un sens du détail. Peinture intérieure et extérieure, pose de papier peint et finitions décoratives. Peintures écologiques disponibles.',
    location: 'bafoussam',
    country: 'CM',
    is_verified: true,
    verifications: ['gov_id', 'phone', 'portfolio'],
    created_at: '2023-09-01T00:00:00Z',
    rating_avg: 4.6,
    review_count: 67,
    completion_rate: 96,
    response_time: 'within 1 hour',
    total_earnings: 2900000,
    balance: 420000,
    pending_earnings: 130000,
    is_available_now: false,
    offers_emergency: false,
    video_intro_url: null,
  },
  {
    id: 'provider-6',
    email: 'marie.atangana@email.com',
    full_name: 'Marie Atangana',
    avatar_url: null,
    role: 'provider',
    phone: '+237 6 88 90 12 34',
    bio: 'Femme de ménage expérimentée et spécialiste de l\'organisation. Nettoyage en profondeur, déménagement, entretien régulier. Produits d\'entretien écologiques utilisés.',
    location: 'douala',
    country: 'CM',
    is_verified: true,
    verifications: ['gov_id', 'phone'],
    created_at: '2023-04-15T00:00:00Z',
    rating_avg: 4.9,
    review_count: 156,
    completion_rate: 99,
    response_time: 'within 1 hour',
    total_earnings: 3600000,
    balance: 540000,
    pending_earnings: 180000,
    is_available_now: true,
    offers_emergency: false,
    video_intro_url: null,
  },
  {
    id: 'provider-7',
    email: 'kouassi.yao@email.com',
    full_name: 'Kouassi Yao',
    avatar_url: null,
    role: 'provider',
    phone: '+225 07 12 34 56',
    bio: 'Mécanicien auto avec 20 ans d\'expérience. Diagnostics complets, réparation moteur, freins, vidange. Tarifs honnêtes et travail de qualité garanti.',
    location: 'abidjan',
    country: 'CI',
    is_verified: true,
    verifications: ['gov_id', 'phone', 'portfolio'],
    created_at: '2022-11-20T00:00:00Z',
    rating_avg: 4.8,
    review_count: 178,
    completion_rate: 97,
    response_time: 'within 2 hours',
    total_earnings: 7200000,
    balance: 1250000,
    pending_earnings: 380000,
    is_available_now: true,
    offers_emergency: true,
    video_intro_url: null,
  },
  {
    id: 'provider-8',
    email: 'joseph.fotso@email.com',
    full_name: 'Joseph Fotso',
    avatar_url: null,
    role: 'provider',
    phone: '+237 6 70 12 34 56',
    bio: 'Menuisier qualifié spécialisé dans les meubles sur mesure, placards encastrés et rénovations. Artisanat de précision avec des bois tropicaux durables.',
    location: 'bamenda',
    country: 'CM',
    is_verified: true,
    verifications: ['gov_id', 'phone', 'portfolio'],
    created_at: '2023-07-12T00:00:00Z',
    rating_avg: 4.9,
    review_count: 92,
    completion_rate: 98,
    response_time: 'within 2 hours',
    total_earnings: 4100000,
    balance: 720000,
    pending_earnings: 210000,
    is_available_now: false,
    offers_emergency: false,
    video_intro_url: null,
  },
];

export const MOCK_CLIENTS: Profile[] = [
  {
    id: 'client-1',
    email: 'ibrahim.djouma@email.com',
    full_name: 'Ibrahim Djouma',
    avatar_url: null,
    role: 'client',
    phone: '+237 6 90 11 22 33',
    bio: null,
    location: 'douala',
    country: 'CM',
    is_verified: false,
    verifications: ['phone'],
    created_at: '2024-01-01T00:00:00Z',
    rating_avg: 0,
    review_count: 0,
    completion_rate: 0,
    response_time: null,
    total_earnings: 0,
    balance: 0,
    pending_earnings: 0,
    is_available_now: false,
    offers_emergency: false,
    video_intro_url: null,
  },
  {
    id: 'client-2',
    email: 'awa.kone@email.com',
    full_name: 'Awa Koné',
    avatar_url: null,
    role: 'client',
    phone: '+225 05 44 55 66',
    bio: null,
    location: 'abidjan',
    country: 'CI',
    is_verified: false,
    verifications: ['phone'],
    created_at: '2024-02-15T00:00:00Z',
    rating_avg: 0,
    review_count: 0,
    completion_rate: 0,
    response_time: null,
    total_earnings: 0,
    balance: 0,
    pending_earnings: 0,
    is_available_now: false,
    offers_emergency: false,
    video_intro_url: null,
  },
];

export const MOCK_GIGS: Gig[] = [
  {
    id: 'gig-1',
    provider_id: 'provider-1',
    title: 'Professional Plumbing Repair & Installation',
    title_fr: 'Réparation et installation de plomberie professionnelle',
    description: 'I provide expert plumbing services including emergency leak repairs, pipe installation, drain cleaning, toilet and faucet repairs, water heater installation, and bathroom remodeling. All work comes with a satisfaction guarantee.',
    description_fr: 'Je fournis des services de plomberie experts incluant les réparations de fuites d\'urgence, l\'installation de tuyauterie, le débouchage, les réparations de toilettes et robinets, l\'installation de chauffe-eau et la rénovation de salles de bain. Tous les travaux sont garantis.',
    category: 'plumbing',
    subcategory: null,
    location: 'douala',
    pricing_tiers: [
      { name: 'Basic', price: 15000, description: 'Simple repair (faucet, toilet, minor leak)', description_fr: 'Réparation simple (robinet, toilette, petite fuite)', delivery_days: 1, features: ['Single fixture repair', 'Parts inspection', '30-day warranty'], features_fr: ['Réparation d\'un appareil', 'Inspection des pièces', 'Garantie 30 jours'] },
      { name: 'Standard', price: 40000, description: 'Medium repair or installation', description_fr: 'Réparation moyenne ou installation', delivery_days: 2, features: ['Up to 3 fixtures', 'Full diagnostic', 'Parts included', '90-day warranty'], features_fr: ['Jusqu\'à 3 appareils', 'Diagnostic complet', 'Pièces incluses', 'Garantie 90 jours'] },
      { name: 'Premium', price: 120000, description: 'Major installation or renovation', description_fr: 'Installation majeure ou rénovation', delivery_days: 5, features: ['Full bathroom/kitchen plumbing', 'Premium materials', 'Code compliance', '1-year warranty', 'Emergency support'], features_fr: ['Plomberie complète salle de bain/cuisine', 'Matériaux premium', 'Conformité aux normes', 'Garantie 1 an', 'Support urgence'] },
    ],
    photos: [],
    video_urls: [],
    rating_avg: 4.9,
    review_count: 127,
    is_active: true,
    is_emergency: true,
    created_at: '2023-04-01T00:00:00Z',
    updated_at: '2024-10-15T00:00:00Z',
    provider: MOCK_PROVIDERS[0],
  },
  {
    id: 'gig-2',
    provider_id: 'provider-2',
    title: 'Residential & Commercial Electrical Services',
    title_fr: 'Services électriques résidentiels et commerciaux',
    description: 'Licensed electrician offering a full range of electrical services. From outlet installation to complete home rewiring. Solar panel setup and energy-efficient solutions available.',
    description_fr: 'Électricienne certifiée offrant une gamme complète de services électriques. De l\'installation de prises à la rénovation complète du câblage. Installation de panneaux solaires et solutions écoénergétiques disponibles.',
    category: 'electrical',
    subcategory: null,
    location: 'abidjan',
    pricing_tiers: [
      { name: 'Basic', price: 20000, description: 'Outlet/switch installation or repair', description_fr: 'Installation ou réparation de prise/interrupteur', delivery_days: 1, features: ['Single outlet/switch', 'Safety inspection', '30-day warranty'], features_fr: ['Une prise/un interrupteur', 'Inspection de sécurité', 'Garantie 30 jours'] },
      { name: 'Standard', price: 75000, description: 'Panel upgrade or circuit installation', description_fr: 'Mise à niveau du panneau ou installation de circuit', delivery_days: 3, features: ['Up to 4 circuits', 'Load balancing', 'Code compliance', '90-day warranty'], features_fr: ['Jusqu\'à 4 circuits', 'Équilibrage de charge', 'Conformité', 'Garantie 90 jours'] },
      { name: 'Premium', price: 200000, description: 'Complete home rewiring or solar setup', description_fr: 'Recâblage complet ou installation solaire', delivery_days: 7, features: ['Whole-home service', 'Solar panel install', 'Inverter setup', '2-year warranty', 'Priority support'], features_fr: ['Service maison complète', 'Installation panneaux solaires', 'Configuration onduleur', 'Garantie 2 ans', 'Support prioritaire'] },
    ],
    photos: [],
    video_urls: [],
    rating_avg: 4.8,
    review_count: 89,
    is_active: true,
    is_emergency: true,
    created_at: '2023-07-15T00:00:00Z',
    updated_at: '2024-11-01T00:00:00Z',
    provider: MOCK_PROVIDERS[1],
  },
  {
    id: 'gig-3',
    provider_id: 'provider-3',
    title: 'Garden Design & Landscape Transformation',
    title_fr: 'Design de jardin et transformation paysagère',
    description: 'Transform your outdoor space into a beautiful tropical garden. I specialize in native plant landscaping, sustainable designs, vegetable gardens, and complete yard makeovers.',
    description_fr: 'Transformez votre espace extérieur en un magnifique jardin tropical. Je me spécialise dans l\'aménagement paysager avec des plantes locales, les designs durables, les potagers et les rénovations complètes de cours.',
    category: 'gardening',
    subcategory: null,
    location: 'yaounde',
    pricing_tiers: [
      { name: 'Basic', price: 25000, description: 'Garden consultation & small planting', description_fr: 'Consultation jardin et petite plantation', delivery_days: 1, features: ['1-hour consultation', 'Plant selection guide', 'Small bed planting'], features_fr: ['Consultation d\'1 heure', 'Guide de sélection des plantes', 'Plantation de petit parterre'] },
      { name: 'Standard', price: 80000, description: 'Medium garden design & installation', description_fr: 'Design et installation de jardin moyen', delivery_days: 4, features: ['Custom design plan', 'Up to 50m²', 'Plants included', 'Irrigation setup'], features_fr: ['Plan de design personnalisé', 'Jusqu\'à 50m²', 'Plantes incluses', 'Installation d\'irrigation'] },
      { name: 'Premium', price: 250000, description: 'Complete landscape transformation', description_fr: 'Transformation paysagère complète', delivery_days: 10, features: ['Full yard design', 'Hardscaping included', 'Irrigation system', 'Lighting', '6-month plant guarantee'], features_fr: ['Design complet de la cour', 'Aménagement dur inclus', 'Système d\'irrigation', 'Éclairage', 'Garantie plantes 6 mois'] },
    ],
    photos: [],
    video_urls: [],
    rating_avg: 5.0,
    review_count: 203,
    is_active: true,
    is_emergency: false,
    created_at: '2023-02-01T00:00:00Z',
    updated_at: '2024-09-20T00:00:00Z',
    provider: MOCK_PROVIDERS[2],
  },
  {
    id: 'gig-4',
    provider_id: 'provider-4',
    title: 'Custom Tailoring & Traditional African Wear',
    title_fr: 'Couture sur mesure et tenues traditionnelles africaines',
    description: 'Expert tailoring services for all your clothing needs. Custom suits and dresses, traditional African outfits (boubou, pagne), wedding attire, and professional alterations.',
    description_fr: 'Services de couture experte pour tous vos besoins vestimentaires. Costumes et robes sur mesure, tenues traditionnelles africaines (boubou, pagne), tenues de mariage et retouches professionnelles.',
    category: 'tailoring',
    subcategory: null,
    location: 'bouake',
    pricing_tiers: [
      { name: 'Basic', price: 8000, description: 'Simple alterations (hem, buttons)', description_fr: 'Retouches simples (ourlet, boutons)', delivery_days: 2, features: ['Basic hemming', 'Button replacement', 'Minor repairs'], features_fr: ['Ourlet basique', 'Remplacement de boutons', 'Réparations mineures'] },
      { name: 'Standard', price: 35000, description: 'Custom outfit or complex alteration', description_fr: 'Tenue sur mesure ou retouche complexe', delivery_days: 7, features: ['Full garment creation', 'Custom fitting', 'Premium thread', 'One revision'], features_fr: ['Création de vêtement complet', 'Ajustement sur mesure', 'Fil premium', 'Une retouche'] },
      { name: 'Premium', price: 100000, description: 'Complete traditional outfit or wedding attire', description_fr: 'Tenue traditionnelle complète ou tenue de mariage', delivery_days: 21, features: ['Custom measurements', 'Fabric selection', 'Multiple fittings', 'Hand-finished details', 'Unlimited revisions'], features_fr: ['Mesures personnalisées', 'Sélection du tissu', 'Plusieurs essayages', 'Finitions à la main', 'Retouches illimitées'] },
    ],
    photos: [],
    video_urls: [],
    rating_avg: 4.7,
    review_count: 45,
    is_active: true,
    is_emergency: false,
    created_at: '2024-02-01T00:00:00Z',
    updated_at: '2024-11-10T00:00:00Z',
    provider: MOCK_PROVIDERS[3],
  },
  {
    id: 'gig-5',
    provider_id: 'provider-5',
    title: 'Interior & Exterior House Painting',
    title_fr: 'Peinture intérieure et extérieure de maison',
    description: 'Professional painting services for homes and businesses. Expert color consultation, surface preparation, and flawless application.',
    description_fr: 'Services de peinture professionnels pour maisons et entreprises. Consultation couleur experte, préparation des surfaces et application impeccable.',
    category: 'painting',
    subcategory: null,
    location: 'bafoussam',
    pricing_tiers: [
      { name: 'Basic', price: 30000, description: 'Single room painting', description_fr: 'Peinture d\'une pièce', delivery_days: 1, features: ['1 room (up to 4x4m)', 'Wall prep included', 'Two coats', 'Paint included'], features_fr: ['1 pièce (jusqu\'à 4x4m)', 'Préparation des murs incluse', 'Deux couches', 'Peinture incluse'] },
      { name: 'Standard', price: 85000, description: 'Multi-room painting', description_fr: 'Peinture de plusieurs pièces', delivery_days: 3, features: ['Up to 3 rooms', 'Color consultation', 'Trim painting', 'Premium paint'], features_fr: ['Jusqu\'à 3 pièces', 'Consultation couleur', 'Peinture des boiseries', 'Peinture premium'] },
      { name: 'Premium', price: 250000, description: 'Whole house painting', description_fr: 'Peinture de maison complète', delivery_days: 7, features: ['Whole house', 'Surface repair', 'Premium paint', 'Detailed trim work', '3-year warranty'], features_fr: ['Maison entière', 'Réparation des surfaces', 'Peinture premium', 'Finitions détaillées', 'Garantie 3 ans'] },
    ],
    photos: [],
    video_urls: [],
    rating_avg: 4.6,
    review_count: 67,
    is_active: true,
    is_emergency: false,
    created_at: '2023-10-01T00:00:00Z',
    updated_at: '2024-08-05T00:00:00Z',
    provider: MOCK_PROVIDERS[4],
  },
  {
    id: 'gig-6',
    provider_id: 'provider-6',
    title: 'Deep Cleaning & Home Organization',
    title_fr: 'Nettoyage en profondeur et organisation de maison',
    description: 'Thorough cleaning and organization services for your home or office. Using eco-friendly products for a complete deep clean.',
    description_fr: 'Services de nettoyage et d\'organisation complets pour votre maison ou bureau. Utilisation de produits écologiques pour un nettoyage en profondeur.',
    category: 'cleaning',
    subcategory: null,
    location: 'douala',
    pricing_tiers: [
      { name: 'Basic', price: 15000, description: 'Standard home cleaning', description_fr: 'Nettoyage standard de maison', delivery_days: 1, features: ['Up to 2 bedrooms', 'Kitchen & bathroom', 'Vacuuming & mopping', 'Green products'], features_fr: ['Jusqu\'à 2 chambres', 'Cuisine et salle de bain', 'Aspirateur et serpillère', 'Produits écologiques'] },
      { name: 'Standard', price: 35000, description: 'Deep cleaning service', description_fr: 'Service de nettoyage en profondeur', delivery_days: 1, features: ['Whole home deep clean', 'Appliance cleaning', 'Window interiors', 'Organization tips'], features_fr: ['Nettoyage profond maison entière', 'Nettoyage des appareils', 'Vitres intérieures', 'Conseils d\'organisation'] },
      { name: 'Premium', price: 75000, description: 'Deep clean + full organization', description_fr: 'Nettoyage profond + organisation complète', delivery_days: 2, features: ['Complete deep clean', 'Closet organization', 'Pantry setup', 'Decluttering', 'Custom storage solutions'], features_fr: ['Nettoyage profond complet', 'Organisation des placards', 'Rangement du garde-manger', 'Désencombrement', 'Solutions de rangement personnalisées'] },
    ],
    photos: [],
    video_urls: [],
    rating_avg: 4.9,
    review_count: 156,
    is_active: true,
    is_emergency: false,
    created_at: '2023-05-15T00:00:00Z',
    updated_at: '2024-11-15T00:00:00Z',
    provider: MOCK_PROVIDERS[5],
  },
  {
    id: 'gig-7',
    provider_id: 'provider-7',
    title: 'Complete Auto Repair & Maintenance',
    title_fr: 'Réparation et entretien automobile complet',
    description: 'Full-service auto repair with transparent pricing. Engine diagnostics, brake service, oil changes, tire rotation, AC repair.',
    description_fr: 'Réparation automobile complète avec tarification transparente. Diagnostics moteur, service de freins, vidanges, rotation des pneus, réparation de climatisation.',
    category: 'auto_repair',
    subcategory: null,
    location: 'abidjan',
    pricing_tiers: [
      { name: 'Basic', price: 10000, description: 'Oil change & basic inspection', description_fr: 'Vidange et inspection de base', delivery_days: 1, features: ['Oil & filter change', '23-point inspection', 'Fluid top-off', 'Tire pressure check'], features_fr: ['Changement d\'huile et filtre', 'Inspection 23 points', 'Complément de liquides', 'Vérification pression pneus'] },
      { name: 'Standard', price: 50000, description: 'Brake service or tune-up', description_fr: 'Service de freins ou mise au point', delivery_days: 2, features: ['Full brake service', 'Diagnostic scan', 'Parts included', '6-month warranty'], features_fr: ['Service de freins complet', 'Scan diagnostic', 'Pièces incluses', 'Garantie 6 mois'] },
      { name: 'Premium', price: 150000, description: 'Major repair or overhaul', description_fr: 'Réparation majeure ou révision', delivery_days: 5, features: ['Engine/transmission work', 'OEM parts', 'Full diagnostic', 'Loaner vehicle', '1-year warranty'], features_fr: ['Travail moteur/transmission', 'Pièces d\'origine', 'Diagnostic complet', 'Véhicule de prêt', 'Garantie 1 an'] },
    ],
    photos: [],
    video_urls: [],
    rating_avg: 4.8,
    review_count: 178,
    is_active: true,
    is_emergency: true,
    created_at: '2022-12-01T00:00:00Z',
    updated_at: '2024-10-25T00:00:00Z',
    provider: MOCK_PROVIDERS[6],
  },
  {
    id: 'gig-8',
    provider_id: 'provider-8',
    title: 'Custom Carpentry & Furniture Building',
    title_fr: 'Menuiserie sur mesure et fabrication de meubles',
    description: 'Handcrafted woodworking for your home. Custom shelving, built-in cabinetry, furniture repair, and more using sustainably sourced tropical hardwoods.',
    description_fr: 'Menuiserie artisanale pour votre maison. Étagères sur mesure, placards encastrés, réparation de meubles et plus encore avec des bois tropicaux durables.',
    category: 'carpentry',
    subcategory: null,
    location: 'bamenda',
    pricing_tiers: [
      { name: 'Basic', price: 20000, description: 'Small repair or simple project', description_fr: 'Petite réparation ou projet simple', delivery_days: 2, features: ['Furniture repair', 'Shelf installation', 'Minor fixes', 'Wood stain match'], features_fr: ['Réparation de meubles', 'Installation d\'étagères', 'Petites réparations', 'Teinte bois assortie'] },
      { name: 'Standard', price: 100000, description: 'Custom shelving or small furniture', description_fr: 'Étagères ou petit meuble sur mesure', delivery_days: 7, features: ['Custom design', 'Quality hardwood', 'Finishing included', 'Delivery & install'], features_fr: ['Design personnalisé', 'Bois dur de qualité', 'Finition incluse', 'Livraison et installation'] },
      { name: 'Premium', price: 350000, description: 'Built-in cabinetry or full room', description_fr: 'Placards encastrés ou pièce complète', delivery_days: 14, features: ['Full custom build', 'Premium materials', '3D design preview', 'Installation', '5-year warranty'], features_fr: ['Construction sur mesure complète', 'Matériaux premium', 'Aperçu design 3D', 'Installation', 'Garantie 5 ans'] },
    ],
    photos: [],
    video_urls: [],
    rating_avg: 4.9,
    review_count: 92,
    is_active: true,
    is_emergency: false,
    created_at: '2023-08-01T00:00:00Z',
    updated_at: '2024-11-05T00:00:00Z',
    provider: MOCK_PROVIDERS[7],
  },
];

export const MOCK_REVIEWS: Review[] = [
  { id: 'review-1', gig_id: 'gig-1', order_id: 'order-1', client_id: 'client-1', provider_id: 'provider-1', rating: 5, comment: 'Jean-Paul est excellent ! Il est arrivé à l\'heure, a diagnostiqué la fuite rapidement et a tout réparé en une heure. Très professionnel. Je recommande vivement !', provider_response: 'Merci Ibrahim ! C\'était un plaisir de travailler avec vous. N\'hésitez pas à me contacter si vous avez besoin de quoi que ce soit.', created_at: '2024-10-20T00:00:00Z', client: MOCK_CLIENTS[0] },
  { id: 'review-2', gig_id: 'gig-1', order_id: 'order-2', client_id: 'client-2', provider_id: 'provider-1', rating: 5, comment: 'Appel d\'urgence à 22h et Jean-Paul était là en 30 minutes. Il a réparé un tuyau éclaté et nous a sauvé de dégâts des eaux importants. Ça valait chaque franc !', provider_response: null, created_at: '2024-09-15T00:00:00Z', client: MOCK_CLIENTS[1] },
  { id: 'review-3', gig_id: 'gig-3', order_id: 'order-3', client_id: 'client-1', provider_id: 'provider-3', rating: 5, comment: 'Amadou a complètement transformé notre cour ! Le design est magnifique et il connaît très bien les plantes adaptées à notre climat. Le jardin est superbe.', provider_response: 'Merci beaucoup ! Votre cour avait un grand potentiel et c\'était un plaisir d\'y travailler. Profitez bien du jardin !', created_at: '2024-11-01T00:00:00Z', client: MOCK_CLIENTS[0] },
  { id: 'review-4', gig_id: 'gig-6', order_id: 'order-4', client_id: 'client-2', provider_id: 'provider-6', rating: 5, comment: 'Marie a fait un travail incroyable de nettoyage en profondeur de notre appartement. Elle a même organisé nos placards. Service vraiment exceptionnel.', provider_response: null, created_at: '2024-10-05T00:00:00Z', client: MOCK_CLIENTS[1] },
  { id: 'review-5', gig_id: 'gig-2', order_id: 'order-5', client_id: 'client-1', provider_id: 'provider-2', rating: 4, comment: 'Excellent travail sur la mise à niveau du panneau électrique. Sarah est très minutieuse et a tout bien expliqué. Un peu plus long que prévu mais la qualité est top.', provider_response: 'Merci pour votre patience Ibrahim. Les mises à niveau de panneaux doivent être faites correctement. Content que vous soyez satisfait !', created_at: '2024-08-20T00:00:00Z', client: MOCK_CLIENTS[0] },
  { id: 'review-6', gig_id: 'gig-7', order_id: 'order-6', client_id: 'client-2', provider_id: 'provider-7', rating: 5, comment: 'Kouassi est le mécanicien le plus honnête avec qui j\'ai travaillé. Il m\'a dit ce dont je n\'avais PAS besoin, me faisant économiser des milliers de francs. Le moteur tourne comme neuf.', provider_response: null, created_at: '2024-09-10T00:00:00Z', client: MOCK_CLIENTS[1] },
];

export const MOCK_BOOKINGS: Booking[] = [
  { id: 'booking-1', gig_id: 'gig-1', client_id: 'client-1', provider_id: 'provider-1', tier: 'Standard', price: 40000, scheduled_date: '2024-12-15', scheduled_time: '10:00', status: 'completed', notes: 'Le robinet de cuisine fuit et le drain de la salle de bain est lent.', created_at: '2024-12-10T00:00:00Z', updated_at: '2024-12-15T16:00:00Z', gig: MOCK_GIGS[0] },
  { id: 'booking-2', gig_id: 'gig-3', client_id: 'client-1', provider_id: 'provider-3', tier: 'Premium', price: 250000, scheduled_date: '2025-01-20', scheduled_time: '09:00', status: 'confirmed', notes: 'Transformation complète de la cour arrière. Je veux des plantes tropicales.', created_at: '2025-01-10T00:00:00Z', updated_at: '2025-01-12T00:00:00Z', gig: MOCK_GIGS[2] },
  { id: 'booking-3', gig_id: 'gig-6', client_id: 'client-2', provider_id: 'provider-6', tier: 'Standard', price: 35000, scheduled_date: '2025-01-25', scheduled_time: '08:00', status: 'in_progress', notes: 'Nettoyage en profondeur de l\'appartement 3 chambres.', created_at: '2025-01-20T00:00:00Z', updated_at: '2025-01-25T08:00:00Z', gig: MOCK_GIGS[5] },
];

export const MOCK_ORDERS: Order[] = [
  { id: 'order-1', booking_id: 'booking-1', client_id: 'client-1', provider_id: 'provider-1', amount: 40000, platform_fee: 4800, provider_earnings: 35200, payment_method: 'mtn_money', payment_intent_id: 'pi_mock_1', payment_status: 'released', status: 'completed', dispute_reason: null, created_at: '2024-12-10T00:00:00Z', completed_at: '2024-12-15T16:00:00Z', booking: MOCK_BOOKINGS[0] },
  { id: 'order-2', booking_id: 'booking-2', client_id: 'client-1', provider_id: 'provider-3', amount: 250000, platform_fee: 30000, provider_earnings: 220000, payment_method: 'orange_money', payment_intent_id: 'pi_mock_2', payment_status: 'held', status: 'in_progress', dispute_reason: null, created_at: '2025-01-10T00:00:00Z', completed_at: null, booking: MOCK_BOOKINGS[1] },
  { id: 'order-3', booking_id: 'booking-3', client_id: 'client-2', provider_id: 'provider-6', amount: 35000, platform_fee: 4200, provider_earnings: 30800, payment_method: 'mtn_money', payment_intent_id: 'pi_mock_3', payment_status: 'held', status: 'in_progress', dispute_reason: null, created_at: '2025-01-20T00:00:00Z', completed_at: null, booking: MOCK_BOOKINGS[2] },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  { id: 'conv-1', participant_1: 'client-1', participant_2: 'provider-1', gig_id: 'gig-1', last_message: 'Merci Jean-Paul ! À lundi à 10h.', last_message_at: '2024-12-12T14:30:00Z', created_at: '2024-12-10T09:00:00Z', other_user: MOCK_PROVIDERS[0], gig: MOCK_GIGS[0], unread_count: 0 },
  { id: 'conv-2', participant_1: 'client-1', participant_2: 'provider-3', gig_id: 'gig-3', last_message: 'Je vous envoie le plan de design demain soir.', last_message_at: '2025-01-15T10:00:00Z', created_at: '2025-01-10T11:00:00Z', other_user: MOCK_PROVIDERS[2], gig: MOCK_GIGS[2], unread_count: 1 },
];

export const MOCK_MESSAGES: Record<string, Message[]> = {
  'conv-1': [
    { id: 'msg-1', conversation_id: 'conv-1', sender_id: 'client-1', content: 'Bonjour Jean-Paul, j\'ai un robinet de cuisine qui fuit et un drain de salle de bain lent. Vous êtes disponible la semaine prochaine ?', is_read: true, created_at: '2024-12-10T09:00:00Z' },
    { id: 'msg-2', conversation_id: 'conv-1', sender_id: 'provider-1', content: 'Bonjour Ibrahim ! Oui, je peux passer lundi matin. Un robinet qui fuit et un drain lent, c\'est dans mon forfait Standard. J\'apporte tous les outils et pièces nécessaires.', is_read: true, created_at: '2024-12-10T09:15:00Z' },
    { id: 'msg-3', conversation_id: 'conv-1', sender_id: 'client-1', content: 'Parfait. Lundi à 10h ça marche pour moi. Qu\'est-ce qui est inclus dans le forfait Standard ?', is_read: true, created_at: '2024-12-10T09:30:00Z' },
    { id: 'msg-4', conversation_id: 'conv-1', sender_id: 'provider-1', content: 'Le forfait Standard couvre jusqu\'à 3 appareils, inclut un diagnostic complet, les pièces et une garantie de 90 jours. C\'est 40 000 FCFA au total.', is_read: true, created_at: '2024-12-10T09:45:00Z' },
    { id: 'msg-5', conversation_id: 'conv-1', sender_id: 'client-1', content: 'Parfait, on fait comme ça. Je réserve maintenant.', is_read: true, created_at: '2024-12-10T10:00:00Z' },
    { id: 'msg-6', conversation_id: 'conv-1', sender_id: 'provider-1', content: 'Réservation confirmée ! Je vous vois lundi à 10h. Assurez-vous que quelqu\'un soit à la maison.', is_read: true, created_at: '2024-12-10T10:05:00Z' },
    { id: 'msg-7', conversation_id: 'conv-1', sender_id: 'client-1', content: 'Merci Jean-Paul ! À lundi à 10h.', is_read: true, created_at: '2024-12-12T14:30:00Z' },
  ],
  'conv-2': [
    { id: 'msg-8', conversation_id: 'conv-2', sender_id: 'client-1', content: 'Bonjour Amadou ! J\'ai vu votre magnifique portfolio. Nous avons une grande cour qui a besoin d\'une rénovation complète. Nous voulons des plantes tropicales.', is_read: true, created_at: '2025-01-10T11:00:00Z' },
    { id: 'msg-9', conversation_id: 'conv-2', sender_id: 'provider-3', content: 'Bonjour Ibrahim ! Merci de me contacter. Les jardins tropicaux sont ma spécialité à Yaoundé. Pouvez-vous m\'envoyer des photos de votre cour et me dire la taille approximative ?', is_read: true, created_at: '2025-01-10T11:30:00Z' },
    { id: 'msg-10', conversation_id: 'conv-2', sender_id: 'client-1', content: 'C\'est environ 150m². Nous voulons un mélange de fleurs tropicales, quelques bacs surélevés pour les légumes et une petite terrasse.', is_read: true, created_at: '2025-01-10T12:00:00Z' },
    { id: 'msg-11', conversation_id: 'conv-2', sender_id: 'provider-3', content: 'Excellent projet ! Je recommande le forfait Premium pour un espace de cette taille. Il inclut le design complet, l\'aménagement de la terrasse, le système d\'irrigation et une garantie plantes de 6 mois.', is_read: true, created_at: '2025-01-10T12:30:00Z' },
    { id: 'msg-12', conversation_id: 'conv-2', sender_id: 'client-1', content: 'Allons-y ! Quand pouvez-vous commencer ?', is_read: true, created_at: '2025-01-10T13:00:00Z' },
    { id: 'msg-13', conversation_id: 'conv-2', sender_id: 'provider-3', content: 'Je vous envoie le plan de design demain soir.', is_read: false, created_at: '2025-01-15T10:00:00Z' },
  ],
};
